spring.application.name=Placement-Tracker
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/placementdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a7e7811d51a6291a134a413d07817eb4
jwt.expiration=86400000
